/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasishowroom;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class showroom extends javax.swing.JFrame {
  public Statement st;
  public ResultSet rs;
  public DefaultTableModel tabmodel;
  public String a;
    
     Connection cn = koneksi.koneksi.getKoneksi();
    public showroom() {
        initComponents();
        judul();
        tampildata();
        reset();
    }

     public void tampildata(){
          try{
            st = cn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tb_showroom");
            while(rs.next()){
                Object[] data = {
                    rs.getString("id_pelanggan"),
                    rs.getString("nama"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("merek_kendaraan"),
                    rs.getString("nama_kendaraan"),
                    rs.getString("hargajual"),
                    rs.getString("jumlah"),
                    rs.getString("total"),
                    rs.getString("uang_pelanggan"),
                    rs.getString("kembalian"),};
                tabmodel.addRow(data);
                }
            } catch (Exception e){
                e.printStackTrace();
        }
    }
  public void judul(){
        Object[] judul = {"id_pelanggan","nama", "jenis_kelamin", "merek_mobil","nama_mobil","hargajual","jumlah","total","uang_pelanggan","kembalian"};
        tabmodel = new DefaultTableModel(null, judul);
        tabmodel2.setModel(tabmodel);
    }
   public void reset(){
        text1.setText("");
        text3.setText("");
        text4.setText("");
        text5.setText("");
        text6.setText("");
        text7.setText("");
        text8.setText("");
        comb1.setSelectedItem("--pilih--");
        buttonGroup1.clearSelection();
        btn1.setEnabled(false);
        btn4.setEnabled(false);
        btn2.setEnabled(true);
        text3.setEnabled(false);
        text6.setEnabled(false);
        text8.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rb2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        text3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        text4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text5 = new javax.swing.JTextField();
        btn2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabmodel2 = new javax.swing.JTable();
        btn1 = new javax.swing.JButton();
        rb3 = new javax.swing.JRadioButton();
        comb1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        text7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        text8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comb2 = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(192, 57, 43));

        jLabel2.setText("ID Pelanggan :");

        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Kelamin :");

        buttonGroup1.add(rb2);
        rb2.setText("Laki Laki");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Merek  Mobil :");

        jLabel7.setBackground(new java.awt.Color(51, 255, 255));
        jLabel7.setText("Kembalian :");

        jLabel9.setText("Jumlah yg di beli :");

        text4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text4ActionPerformed(evt);
            }
        });
        text4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text4KeyReleased(evt);
            }
        });

        jLabel10.setText("Harga Jual Kendaraan:");

        btn2.setText("Simpan");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn4.setText("Hapus");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        tabmodel2.setAutoCreateRowSorter(true);
        tabmodel2.setBackground(new java.awt.Color(204, 204, 204));
        tabmodel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Pelanggan", "Nama", "Jenis Kelamin", "Merek Mobil", "Nama Mobil", "Harga Jual", "Jumlah yang di beli", "Total", "Uang Pelanggan", "Kembalian"
            }
        ));
        tabmodel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabmodel2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabmodel2);

        btn1.setText("Update");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb3);
        rb3.setText("Perempuan");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });

        comb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih--", "Toyota", "Daihatsu", "Mitsubishi", "Ford", "Nissan" }));
        comb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comb1ItemStateChanged(evt);
            }
        });
        comb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Nama Mobil :");

        jLabel5.setText("Uang Pelanggan :");

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Nama  :");

        jLabel12.setText("Total :");

        jButton2.setText("Hitung Total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hitung Kembalian");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel1.setText("Uas Praktik PBO");

        jLabel6.setBackground(new java.awt.Color(51, 255, 255));
        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        jLabel6.setText("202101096 - Pranajaya S. B");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(jLabel6)
                .addContainerGap(427, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(410, 410, 410))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        comb2.setEditable(true);
        comb2.setMaximumRowCount(3);
        comb2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comb2ItemStateChanged(evt);
            }
        });
        comb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comb2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(comb1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text7, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel10))
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(text4, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addComponent(text3, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addComponent(text8))
                            .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(201, 201, 201))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(19, 19, 19)
                        .addComponent(rb2)
                        .addGap(18, 18, 18)
                        .addComponent(rb3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(257, 257, 257))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(244, 244, 244))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(text8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(text7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rb2)
                            .addComponent(rb3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(comb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(text6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2)
                    .addComponent(jButton1)
                    .addComponent(btn4)
                    .addComponent(btn1))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text4ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (text1.getText().equals("") || text7.getText().equals("") || a.equals("") ||  text3.getText().equals("") ||  text4.getText().equals("") ||  text5.getText().equals("") ||  text8.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Data Masih Ada Yang Kosong!!!!!");
        }else{
        try{
            
         st = cn.createStatement();
            st.executeUpdate("INSERT INTO tb_showroom SET id_pelanggan='" + text1.getText() + "', nama_kendaraan='" +comb2.getSelectedItem() +"', hargajual='" + text3.getText() + "', jumlah='" + text4.getText() +"', uang_pelanggan='" + text5.getText()+"', kembalian='" + text6.getText() + "' , jenis_kelamin='" + a + "' , merek_kendaraan='" + comb1.getSelectedItem() +"', nama='" + text7.getText() + "',total='" + text8.getText()+"'");
            tampildata();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Save!!!!!");
            text1.setText("");
            text3.setText("");
            text4.setText("");
            text5.setText("");
            text6.setText("");
            text7.setText("");
            text8.setText("");
            buttonGroup1.clearSelection();
            comb1.setSelectedItem("--pilih--");
        } catch(Exception e){
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
           if (text1.getText().equals("") || text7.getText().equals("") || a.equals("")||  text3.getText().equals("") ||  text4.getText().equals("") ||  text5.getText().equals("") ||  text8.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Data Masih Ada Yang Kosong!!!!!");
        }else{
        try{
            if (rb2.isSelected()){
                a = rb2.getText();
            }else if (rb3.isSelected()){
                a = rb3.getText();
            }else {
                JOptionPane.showMessageDialog(null, "!!!!!EROR!!!!!");
            }
            String where = tabmodel.getValueAt(tabmodel2.getSelectedRow(), 0)+ "";
            st = cn.createStatement();
            st.executeUpdate("UPDATE tb_showroom SET nama_kendaraan='" + "', hargajual='" + text3.getText() + "', jumlah='" + text4.getText() +"', uang_pelanggan='" + text5.getText()+"', kembalian='" + text6.getText() + "' , jenis_kelamin='" + a + "' , merek_kendaraan='" + comb1.getSelectedItem() +"', nama='" + text7.getText() + "',total='" + text8.getText()+"' WHERE id_pelanggan='" + where + "';");
            reset();
            JOptionPane.showMessageDialog(null, "data berhasl di ubah");
            tampildata();
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn1ActionPerformed
    }
    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
 try{
            int jawab;
            if((jawab = JOptionPane.showConfirmDialog(null, "Yakin ingin di delete?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0){
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM tb_showroom WHERE id_pelanggan='" + tabmodel.getValueAt(tabmodel2.getSelectedRow(), 0) + "'" );
                tampildata();
                reset();
            }   
        } catch(Exception e){
            e.printStackTrace();
        }       
    }//GEN-LAST:event_btn4ActionPerformed

    private void comb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb1ActionPerformed
  
    }//GEN-LAST:event_comb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        a = rb2.getText();
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
        // TODO add your handling code here:
        a = rb3.getText();
    }//GEN-LAST:event_rb3ActionPerformed

    private void comb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comb1ItemStateChanged
        if(comb1.getSelectedItem().equals("Toyota")){
                comb2.addItem("Avanza");
                comb2.addItem("Corolla");
                comb2.addItem("Fortuner");
                comb2.setSelectedItem("Avanza");
        }else if(comb1.getSelectedItem().equals("Daihatsu")){
            comb2.addItem("Grand Max");
            comb2.addItem("Xenia");
            comb2.addItem("Terios");
            comb2.setSelectedItem("Grand Max");
        }else if(comb1.getSelectedItem().equals("Mitsubishi")){
            comb2.addItem("Pajero Sport");
            comb2.addItem("Xpander");
            comb2.addItem("L300");
            comb2.setSelectedItem("Pajero Sport");
        }else if(comb1.getSelectedItem().equals("Ford")){
            comb2.addItem("Eco Sport");
            comb2.addItem("Ranger");
            comb2.addItem("Mustang");
            comb2.setSelectedItem("Eco Sport");
        }else if(comb1.getSelectedItem().equals("Nissan")){
          
            comb2.addItem("Grand Livina");
            comb2.addItem("Serena");
            comb2.addItem("Evalia");
            comb2.setSelectedItem("Grand Livina");
        }
    }//GEN-LAST:event_comb1ItemStateChanged

    private void tabmodel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabmodel2MouseClicked
        text1.setText(tabmodel.getValueAt(tabmodel2.getSelectedRow(), 0)+ "");
        text7.setText(tabmodel.getValueAt(tabmodel2.getSelectedRow(), 1)+ "");
        a = tabmodel.getValueAt(tabmodel2.getSelectedRow(), 2)+ "";
      switch (a) {
          case "Laki Laki":
              rb2.setSelected(true);
              break;
          case "Perempuan":
              rb3.setSelected(true);
              break;
          default:
              JOptionPane.showMessageDialog(null, "EROR");
              break;
      }
        comb1.setSelectedItem(tabmodel.getValueAt(tabmodel2.getSelectedRow(), 3)+ "");
        text3.setText(tabmodel.getValueAt(tabmodel2.getSelectedRow(), 5)+ "");
        text4.setText(tabmodel.getValueAt(tabmodel2.getSelectedRow(), 6)+ "");
        text8.setText(tabmodel.getValueAt(tabmodel2.getSelectedRow(), 7)+ "");
        text5.setText(tabmodel.getValueAt(tabmodel2.getSelectedRow(), 8)+ "");
        text6.setText(tabmodel.getValueAt(tabmodel2.getSelectedRow(), 9)+ "");
     
        
        
        
        btn1.setEnabled(true);
        btn2.setEnabled(false);
        btn4.setEnabled(true);
        
        jButton1.setEnabled(true);
    }//GEN-LAST:event_tabmodel2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if (text3.getText().equals("") || text4.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Data Masih Ada Yang Kosong!!!!!");
        }else{
            int angka1,angka2,hasil;
       
        //input nilai
        angka1 = Integer.parseInt(text3.getText());
        angka2 = Integer.parseInt(text4.getText());
       
        //ru;mus
        hasil = angka1 * angka2;
       
         //output
        text8.setText(Integer.toString(hasil));
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         if (text5.getText().equals("") ) {
            JOptionPane.showMessageDialog(null, "Isi dulu data yang kosong !!!!");
        }else{
            int angka1,angka2,hasil;
       
        //input nilai
        angka1 = Integer.parseInt(text8.getText());
        angka2 = Integer.parseInt(text5.getText());
       
        //ru;mus
        hasil = angka2 - angka1;
       
         //output
        text6.setText(Integer.toString(hasil));
         }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text1ActionPerformed

    private void comb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb2ActionPerformed

    private void comb2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comb2ItemStateChanged
     if (comb2.getSelectedItem().equals("Avanza")){
     text3.setText("180000000");
     }else if (comb2.getSelectedItem().equals("Corolla")){
     text3.setText("100000000");
     }else if (comb2.getSelectedItem().equals("Fortuner")){
     text3.setText("200000000");
     }else if (comb2.getSelectedItem().equals("Grand Max")){
     text3.setText("150000000");
     }else if (comb2.getSelectedItem().equals("Xenia")){
     text3.setText("180000000");
     }else if (comb2.getSelectedItem().equals("Terios")){
     text3.setText("200000000");
     }else if (comb2.getSelectedItem().equals("Pajero Sport")){
     text3.setText("250000000");
     }else if (comb2.getSelectedItem().equals("L300")){
     text3.setText("150000000");
     }else if (comb2.getSelectedItem().equals("Eco Sport")){
     text3.setText("170000000");
     }else if (comb2.getSelectedItem().equals("Ranger")){
     text3.setText("120000000");
     }else if (comb2.getSelectedItem().equals("Mustang")){
     text3.setText("520000000");
     }else if (comb2.getSelectedItem().equals("Grand Livina")){
     text3.setText("170000000");
     }else if (comb2.getSelectedItem().equals("Ranger")){
     text3.setText("120000000");
     }else if (comb2.getSelectedItem().equals("Evalia")){
     text3.setText("180000000");
     }
    }//GEN-LAST:event_comb2ItemStateChanged

    private void text4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_text4KeyReleased
                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showroom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comb1;
    private javax.swing.JComboBox<String> comb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JTable tabmodel2;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text6;
    private javax.swing.JTextField text7;
    private javax.swing.JTextField text8;
    // End of variables declaration//GEN-END:variables
}
